export type ResearchItem = {
  id: string;
  title: string;
  category: string;
  venue: string;
  status: "Published" | "Accepted" | "Accepted for Publication" | "Proceedings" | "Presented" | "Accepted and Presented" | "In Press" | "Proposal Accepted";
  year: number;
  authors: string;
  doi?: string;
};

export const RESEARCH_ITEMS: ResearchItem[] = [
  {
    id: "r1",
    title: "Predictive Modelling for Chronic Kidney Disease",
    category: "Applied AI in Healthcare and Biomedical Engineering",
    venue: "IEEE IEMENTech",
    status: "Proceedings",
    year: 2025,
    authors: "Apurba Nandi, Priyanka Paul, Avik Kumar Das, Arijeet Ghosh, Anjali Singh, Aayush Gupta",
  },
  {
    id: "r2",
    title: "Judicious Use of Anti-VEGF in Diabetic Macular Edema",
    category: "Applied AI in Healthcare and Biomedical Engineering",
    venue: "Scientific Reports, Nature Springer (Q1)",
    status: "Published",
    year: 2025,
    authors: "Anwesha Mondal, Apurba Nandi, Subhasish Pramanik, Lakshmi Kanta Mondal",
  },
  {
    id: "r3",
    title: "Alzheimer's Disease Detection via ML",
    category: "Applied AI in Healthcare and Biomedical Engineering",
    venue: "Springer IESIA",
    status: "Accepted for Publication",
    year: 2025,
    authors: "Faishal Abrar, Apurba Nandi, Sangita Dutta, Sandip Mandal",
  },
  {
    id: "r4",
    title: "Gestational Diabetes Prediction using Meta Learning and XAI",
    category: "Applied AI in Healthcare and Biomedical Engineering",
    venue: "Springer ICACCP",
    status: "Accepted for Publication",
    year: 2025,
    authors: "Yashraj Sharma, Suvajit Majhi, Rekharani Mahanta, Avik Kumar Das, Apurba Nandi",
  },
  {
    id: "r5",
    title: "Brain Tumour Diagnosis with Ensemble Deep Learning Technique",
    category: "Applied AI in Healthcare and Biomedical Engineering",
    venue: "Springer AISC",
    status: "Accepted for Publication",
    year: 2025,
    authors: "Apurba Nandi, Tista Mukherjee, Soumika Das, Nitu Saha, Sayantani Das, Sandip Mandal",
  },
  {
    id: "r6",
    title: "Cognitive Load Estimation Using Deep Neural Networks",
    category: "Applied AI in Healthcare and Biomedical Engineering",
    venue: "Cognitive Neurodynamics Journal (Springer Nature)",
    status: "Published",
    year: 2025,
    authors: "Shaoni Banerjee, Priyanka Paul, Apurba Nandi, Avik Kumar Das, Arijeet Ghosh",
  },
  {
    id: "r7",
    title: "Adaptive AI-Driven Federated Learning for Secure and Efficient IoT-Based Healthcare Systems",
    category: "Applied AI in Healthcare and Biomedical Engineering",
    venue: "Bentham Science",
    status: "Accepted",
    year: 2025,
    authors: "Sudeshna Dey, Siddhartha Chatterjee, Ahona Ghosh, Ananya Sarkar",
  },
  {
    id: "r8",
    title: "A Paradigm Shift in EEG Analysis: Comparing Machine Learning Models for Automated Seizure Classification",
    category: "Applied AI in Healthcare and Biomedical Engineering",
    venue: "Wiley",
    status: "Accepted",
    year: 2025,
    authors: "Uddipan Ghosh, Ahona Ghosh, Rangon Sarkar, Debdutta Ghosh, Hritwika Roy",
  },
  {
    id: "r9",
    title: "TriNetDerm: An Ensemble Deep Learning Method for Robust Skin Cancer Classification",
    category: "Applied AI in Healthcare and Biomedical Engineering",
    venue: "ICRCICN",
    status: "Published",
    year: 2025,
    authors: "Sayantani Das, Nitu Saha, Pranati Mondal, Sumit Mondal, Dwaipyan Ghosh, Sneha Pramanik, Swapnendu Biswas, Sohini Patra, Singhan Ganguly, Chinmoy Ghorai",
  },
  {
    id: "r10",
    title: "GuardNet: A Deep Learning-Based Real-Time Surveillance System for Face Obscuration, Abnormal Posture, and Weapon Detection Using YOLOv8 and Pose-Based Behavior Analysis",
    category: "Applied AI in Healthcare and Biomedical Engineering",
    venue: "Bentham Science",
    status: "Accepted",
    year: 2025,
    authors: "Uddipan Ghosh, Apurba Nandi, Ayush Shaw, Yashraj Singh",
  },
  {
    id: "r11",
    title: "An Efficient Deep Learning Approach for Real-Time Weapon Detection in Static Images Based on YOLOv8",
    category: "Applied AI in Healthcare and Biomedical Engineering",
    venue: "IEEE MPCON",
    status: "Presented",
    year: 2026,
    authors: "Uddipan Ghosh, Apurba Nandi, Sandip Mandal, Pragya Shree, Avik Kumar Das, Sangita Dutta",
  },
  {
    id: "r12",
    title: "Bishnupur Architecture Analysis and Tourism Enhancement with Deep Learning",
    category: "Tourism and Sustainability",
    venue: "IEEE INDISCON",
    status: "Published",
    year: 2025,
    authors: "Apurba Nandi, Avik Kumar Das, Tuheena Bose, Divyanshi Srivastava, Sandip Mandal, Madhurya Chowdhury",
  },
  {
    id: "r13",
    title: "Spatial Distribution Modeling of Panthera tigris for Conservation Planning in India",
    category: "Tourism and Sustainability",
    venue: "IEEE CCPIS",
    status: "Proceedings",
    year: 2025,
    authors: "Akash Mondal, Ankur Saha, Arijeet Ghosh, Sudipta Dey, Sreya Ghosh, Avik Kr. Das",
    doi: "10.1109/CCPIS65231.2025.11233987",
  },
  {
    id: "r14",
    title: "Fuzzy AI for Riverbank Health Monitoring",
    category: "Tourism and Sustainability",
    venue: "Springer ICDMIS",
    status: "Accepted for Publication",
    year: 2025,
    authors: "Apurba Nandi, Anjali Singh, Aasish Shrestha, Tanisha Pan, Anwesha Das, Avik Kumar Das",
  },
  {
    id: "r15",
    title: "Student-Alumni Networking via DQN and Graph Intelligence",
    category: "AI-Driven Intelligent Systems and Platforms",
    venue: "IEEE INCIP",
    status: "Proceedings",
    year: 2025,
    authors: "N. Kundu, G. Mandal, A. Bhandari, U. Bhaskar, Apurba Nandi",
    doi: "10.1109/INCIP64058.2025.11019749",
  },
  {
    id: "r16",
    title: "Job Recommendation Using Real-Time Skills and Trends",
    category: "AI-Driven Intelligent Systems and Platforms",
    venue: "IEEE CIACON",
    status: "Accepted for Publication",
    year: 2025,
    authors: "Apurba Nandi, Avik Kumar Das, Hritajit Sur, Sankalpa Dutta, Arijeet Das, Shuvam Podder",
  },
  {
    id: "r17",
    title: "Firewall Defense via Reinforcement Learning",
    category: "AI-Driven Intelligent Systems and Platforms",
    venue: "Bentham Science Book Chapter",
    status: "Accepted for Publication",
    year: 2025,
    authors: "Apurba Nandi, Uddipan Ghosh, Sangita Dutta, Sandip Mandal, Avik Kumar Das, Arijeet Ghosh",
  },
  {
    id: "r18",
    title: "Graph-Based Student-Alumni Engagement",
    category: "AI-Driven Intelligent Systems and Platforms",
    venue: "Springer RAISAA",
    status: "Accepted for Publication",
    year: 2024,
    authors: "Danisha Basu, Hritajit Sur, Dwaipyan Ghosh, Aritra Das, Apurba Nandi, Arijeet Ghosh",
  },
  {
    id: "r19",
    title: "Overlapping Pairwise Chunking and Merging for Long Context Summarization in LLMs",
    category: "AI-Driven Intelligent Systems and Platforms",
    venue: "IEEE SCRS AIC",
    status: "Accepted for Publication",
    year: 2025,
    authors: "Avik Kumar Das, Subhajit Ghosh",
  },
  {
    id: "r20",
    title: "Tracking the Tides of Toxicity: Temporal Shifts in Public Emotion and Discourse During the COVID-19 Crisis",
    category: "AI-Driven Intelligent Systems and Platforms",
    venue: "IEEE ACROSET",
    status: "Published",
    year: 2025,
    authors: "Uddipan Ghosh, Sangita Dutta, Indrajit Mondal, Apurba Nandi, Avik Kumar Das",
    doi: "10.1109/ACROSET66531.2025.11280719",
  },
  {
    id: "r21",
    title: "JobLinker: Automated Recruitment through Verified Intelligence",
    category: "AI-Driven Intelligent Systems and Platforms",
    venue: "IEEE ICAECT",
    status: "Published",
    year: 2026,
    authors: "Uddipan Ghosh, Apalok Roy, Subhabrata Sarkar, Indrashish Bhattacharya, Soumabho Ghosh, Satakshi Shandilya",
    doi: "10.1109/ICAECT68478.2026.11425949",
  },
  {
    id: "r22",
    title: "A Hybrid Framework for Sentiment Analysis on Textual Data Using BERT Embeddings and Random Forest Classifier",
    category: "AI-Driven Intelligent Systems and Platforms",
    venue: "IEEE ICAECT",
    status: "Published",
    year: 2026,
    authors: "Uddipan Ghosh, Suvobrata Sarkar, Susovan Jana, Indrashish Bhattacharya, Kishan Singh, Priyanka Kumari",
    doi: "10.1109/ICAECT68478.2026.11426001",
  },
  {
    id: "r23",
    title: "Real-Time Threat Intelligence and Automated Prevention Using Micro Intelligent System Technology and Explainable Tree-Based Models",
    category: "AI-Driven Intelligent Systems and Platforms",
    venue: "IEEE IEMENTECH",
    status: "Published",
    year: 2026,
    authors: "Uddipan Ghosh, Ankan Sarkar, Siddhartha Roy, Apurba Nandi, Avik Kumar Das, Pratik Saha",
    doi: "10.1109/IEMENTech202669403.2026.11434400",
  },
  {
    id: "r24",
    title: "Real-Time Detection and Explainable Analysis of Unsafe URLs Using CatBoost and Random Forest Ensembles",
    category: "AI-Driven Intelligent Systems and Platforms",
    venue: "IEEE IEMENTECH",
    status: "Published",
    year: 2026,
    authors: "Uddipan Ghosh, Ankan Sarkar, Siddhartha Roy, Apurba Nandi, Avik Kumar Das, Pratik Saha",
    doi: "10.1109/IEMENTech202669403.2026.11434080",
  },
  {
    id: "r25",
    title: "Micro Intelligent System Technology for Adaptive Firewall Defence",
    category: "AI-Driven Intelligent Systems and Platforms",
    venue: "Bentham Science",
    status: "Accepted",
    year: 2025,
    authors: "Uddipan Ghosh, Apurba Nandi, Sangita Dutta, Sandip Mandal, Avik Kumar Das, Arijeet Ghosh",
  },
  {
    id: "r26",
    title: "Revolutionizing E-Commerce Using MIST-AI and AI-Driven Cloud Networking Frameworks",
    category: "AI-Driven Intelligent Systems and Platforms",
    venue: "Bentham Science",
    status: "Accepted",
    year: 2025,
    authors: "Uddipan Ghosh, Apurba Nandi, Sangita Dutta, Sandip Mandal, Avik Kumar Das, Arijeet Ghosh",
  },
  {
    id: "r27",
    title: "MindWatch: Next-Generation Wearable Framework for Stress Monitoring and Prediction",
    category: "AI-Driven Intelligent Systems and Platforms",
    venue: "IEMECON",
    status: "Proceedings",
    year: 2025,
    authors: "Akash Mondal, Arijeet Ghosh, S. Dey, S. Mandal, A.K. Das, S. Dutta",
    doi: "10.1109/IEMECON69302.2025.11365881",
  },
  {
    id: "r28",
    title: "Cloud-Integrated Stealth Network Scanning for Vulnerability Assessment Using GoScan and ARP Tracking",
    category: "AI-Driven Intelligent Systems and Platforms",
    venue: "ICIDA",
    status: "Accepted and Presented",
    year: 2025,
    authors: "Siddhartha Roy, Subhaditya Roy, Abeer Lal Nandi",
  },
  {
    id: "r29",
    title: "Homomorphic Encryption Optimization in Real-Time IoT Healthcare Based on Adaptive Machine Learning and Explainable Artificial Intelligence",
    category: "AI-Driven Intelligent Systems and Platforms",
    venue: "S04: Advances in Data Science for NLP, VANET, and Computational Biology",
    status: "Accepted and Presented",
    year: 2025,
    authors: "Siddhartha Roy, Raisa Santra, Ritisha Dhar, Ahona Ghosh, Arundhati Roy",
  },
  {
    id: "r30",
    title: "Stock Forecasting Using Bi-LSTM-GRU Hybrid Model",
    category: "Financial Forecasting and Economic Intelligence",
    venue: "Taylor and Francis IRTM",
    status: "Accepted for Publication",
    year: 2024,
    authors: "Shaoni Banerjee, Hansa Ray, Shubhanshu Tiwari, Khizra Aslam, Apurba Nandi, Avik Kumar Das",
  },
  {
    id: "r31",
    title: "Gold Stock Forecasting with FinBERT and Federated Learning",
    category: "Financial Forecasting and Economic Intelligence",
    venue: "Springer ICDMIS",
    status: "Accepted for Publication",
    year: 2025,
    authors: "Apurba Nandi, Pratyay Ghosh, Kuntal Roy, Puspak Samanta, Diptadip Choudhury, Anwesha Ghosh",
  },
  {
    id: "r32",
    title: "Explainable AI for Fuel and Energy Consumption",
    category: "Financial Forecasting and Economic Intelligence",
    venue: "Springer Book: Internet of Vehicles",
    status: "Accepted for Publication",
    year: 2025,
    authors: "Apurba Nandi, Sandip Mandal, Sayantani Das, Arijeet Ghosh, Avik Kumar Das",
  },
  {
    id: "r33",
    title: "LSTM-Based E-commerce Sales Prediction",
    category: "Financial Forecasting and Economic Intelligence",
    venue: "CRC Press, Taylor and Francis Group, USA",
    status: "Published",
    year: 2026,
    authors: "Sangita Dutta, Dr. Siddhartha Roy",
  },
  {
    id: "r34",
    title: "AI in Drug Discovery and Telemedicine",
    category: "Financial Forecasting and Economic Intelligence",
    venue: "De Gruyter Publishers (Scopus Indexed)",
    status: "Published",
    year: 2025,
    authors: "Dr. Siddhartha Roy",
  },
  {
    id: "r35",
    title: "Cognitive Load Estimation Using Deep Neural Networks",
    category: "Neuroscience and Cognitive AI",
    venue: "Cognitive Neurodynamics Journal (Springer Nature)",
    status: "Published",
    year: 2025,
    authors: "Shaoni Banerjee, Priyanka Paul, Apurba Nandi, Avik Kumar Das, Arijeet Ghosh",
  },
  {
    id: "r36",
    title: "A Paradigm Shift in EEG Analysis: Comparing Machine Learning Models for Automated Seizure Classification",
    category: "Neuroscience and Cognitive AI",
    venue: "Wiley",
    status: "Accepted",
    year: 2025,
    authors: "Uddipan Ghosh, Ahona Ghosh, Rangon Sarkar, Debdutta Ghosh, Hritwika Roy",
  },
  {
    id: "r37",
    title: "Design of IoT Enabled Smart Agriculture System Using Automated Vehicle",
    category: "Agriculture",
    venue: "IEEE INDISCON",
    status: "Accepted for Publication",
    year: 2025,
    authors: "Arka Mahajan, Ishika Haldar, Srishti Srinjan, Debajyoti Chatterjee, Suchanda Chatterjee",
  },
  {
    id: "r38",
    title: "Phytosense: A Lightweight System for Real-Time Plant Disease Detection",
    category: "Agriculture",
    venue: "ICDAI, Springer",
    status: "Accepted for Publication",
    year: 2025,
    authors: "Akash Mondal, Sudipta Dey, Arijeet Ghosh, Sreya Ghosh, Apurba Nandi, Kiran Ghosh",
  },
  {
    id: "r39",
    title: "AgroFog+: Integrated IoT and AI System for Smart Greenhouse Management",
    category: "Agriculture",
    venue: "IEMECON",
    status: "Proceedings",
    year: 2025,
    authors: "Shibagni Bhattacharjee, Raj Krish, Debajyoti Chatterjee, Suchanda Chatterjee",
  },
  {
    id: "r40",
    title: "A Novel Framework of Internet of Nano Things for Pre-symptomatic Plant Pathogen Detection Using ROS-Sensitive Nanofibers and Deep Learning",
    category: "Agriculture",
    venue: "CRC Press",
    status: "Accepted",
    year: 2025,
    authors: "Uddipan Ghosh, Ahona Ghosh, Rangon Sarkar, Cherry Ghosh, Awantika Kumari",
  },
  {
    id: "r41",
    title: "Blockchain for Secure E-Voting Systems",
    category: "Secure Systems and Data Integrity",
    venue: "ICDMIS, Springer",
    status: "Accepted for Publication",
    year: 2024,
    authors: "Siddhartha Roy",
  },
  {
    id: "r42",
    title: "Transforming Crowdfunding with Blockchain",
    category: "Secure Systems and Data Integrity",
    venue: "ICICC, Elsevier SSRN",
    status: "Accepted for Publication",
    year: 2025,
    authors: "Dr. Siddhartha Roy, Adarsh Giri, Yash Kumar Giri, Akash Mondal, Md Asid Khan",
  },
  {
    id: "r43",
    title: "Transparency and Trust for Religious Organizations",
    category: "Secure Systems and Data Integrity",
    venue: "ICDMIS, Springer",
    status: "Accepted for Publication",
    year: 2025,
    authors: "Dr. Siddhartha Roy, Adarsh Giri, Yash Kumar Giri, Akash Mondal, Md Asid Khan",
  },
  {
    id: "r44",
    title: "Micro Intelligent System Technology for Adaptive Firewall Defense",
    category: "Secure Systems and Data Integrity",
    venue: "Bentham Science",
    status: "Accepted for Publication",
    year: 2025,
    authors: "Apurba Nandi, Uddipan Ghosh, Sangita Dutta, Sandip Mandal, Avik Kumar Das, Arijeet Ghosh",
  },
  {
    id: "r45",
    title: "Cloud-Integrated Stealth Network Scanning for Vulnerability Assessment Using GoScan and ARP Tracking",
    category: "Secure Systems and Data Integrity",
    venue: "ICIDA",
    status: "Accepted and Presented",
    year: 2025,
    authors: "Siddhartha Roy, Subhaditya Roy, Abeer Lal Nandi",
  },
  {
    id: "r46",
    title: "Homomorphic Encryption Optimization in Real-Time IoT Healthcare Based on Adaptive Machine Learning and Explainable Artificial Intelligence",
    category: "Secure Systems and Data Integrity",
    venue: "VANET and Computational Biology Conference",
    status: "Accepted and Presented",
    year: 2025,
    authors: "Siddhartha Roy, Raisa Santra, Ritisha Dhar, Ahona Ghosh, Arundhati Roy",
  },
  {
    id: "r47",
    title: "Photoluminescence Prediction in Silicon Nanostructures",
    category: "Applied Physics and NanoTech",
    venue: "ICDMAI, Springer",
    status: "Accepted for Publication",
    year: 2025,
    authors: "Siddhartha Roy, Susmita Biswas",
  },
  {
    id: "r48",
    title: "Predictive Modeling of Photoluminescence Spectrum",
    category: "Applied Physics and NanoTech",
    venue: "AdComsys, Springer",
    status: "Accepted for Publication",
    year: 2025,
    authors: "Susmita Biswas, Siddartha Roy, Rangoon Sarkar, Raisa Santra",
  },
  {
    id: "r49",
    title: "Deep LSTM-Driven Framework for Capturing Complex Temporal Dependencies in Proteomic Time-Series Data",
    category: "Applied Physics and NanoTech",
    venue: "10th ICDMAI",
    status: "Accepted and Presented",
    year: 2026,
    authors: "Siddhartha Roy, Raisa Santra, Rangon Sarkar, Tejashri Srivastava, Arundhati Roy",
  },
  {
    id: "r50",
    title: "Optimization and Comparison of Machine Learning Models for Predictive Modeling of Photoluminescence Spectrum of Freestanding Colloidal Silicene Ink",
    category: "Applied Physics and NanoTech",
    venue: "AdComSys",
    status: "Accepted and Presented",
    year: 2025,
    authors: "Susmita Biswas, Siddhartha Roy, Rangon Sarkar",
  },
  {
    id: "r51",
    title: "Translational Roadmap of Intelligent Nanobots in Diabetes Therapy",
    category: "Applied Physics and NanoTech",
    venue: "Scrivener",
    status: "Accepted for Publication",
    year: 2025,
    authors: "Siddhartha Roy, Susmita Biswas, Rangan Sarkar, Samrik Gosh, Arghadeep Giri, Samadrita Hazra",
  },
  {
    id: "r52",
    title: "Nanobots in Cancer Therapy and Drug Delivery",
    category: "Applied Physics and NanoTech",
    venue: "Scrivener",
    status: "Accepted for Publication",
    year: 2025,
    authors: "Susmita Biswas, Siddhartha Roy, Rangon Sarkar, Ahona Ghosh, Samrik Gosh, Arghadeep Giri, Samadrita Hazra",
  },
  {
    id: "r53",
    title: "Circuit Obfuscation in Grover's Algorithm through Gate-Level Camouflage",
    category: "Applied Physics and NanoTech",
    venue: "Quantumkol",
    status: "Accepted and Presented",
    year: 2025,
    authors: "Siddhartha Roy, Rohan Sarkar, Kaustav Dutta",
  },
  {
    id: "r54",
    title: "Machine Learning Optimized Trident Monopole Antenna for WLAN/WiMAX Applications",
    category: "Applied Physics and NanoTech",
    venue: "IEMENTECH",
    status: "Accepted for Publication",
    year: 2026,
    authors: "Debajyoti Chatterjee, Anjan Kumar Kundu, Suchanda Chatterjee",
  },
  {
    id: "r55",
    title: "The Practical Implementations of Microwave Devices for IoMT, Wearable, Sensors and Healthcare Applications",
    category: "Applied Physics and NanoTech",
    venue: "CRC Press book on RF and Microwave Design",
    status: "Published",
    year: 2025,
    authors: "Anjan Kumar Kundu, Suchanda Das, Anusuya Nandi, Sanjana Banerjee",
  },
  {
    id: "r56",
    title: "Design of Passive IRS Meta-Atoms for High-Gain Beamforming and Capacity Enhancement",
    category: "Applied Physics and NanoTech",
    venue: "INCOWOCO, IEEE",
    status: "Published",
    year: 2025,
    authors: "Chameli Mitra, Sudipta Dey, Arijeet Ghosh, Iti Saha Misra",
    doi: "10.1109/InCoWoCo68239.2025.11407269",
  },
  {
    id: "r57",
    title: "Meta-Deep Learning for Fuel Analytics",
    category: "Interdisciplinary AI-Driven Systems",
    venue: "Springer Book Chapter: Internet of Vehicles",
    status: "Accepted for Publication",
    year: 2025,
    authors: "Apurba Nandi, Sandip Mandal, Sayantani Das, Arijeet Ghosh, Avik Kumar Das",
  },
  {
    id: "r58",
    title: "Attention-Enhanced Deep Learning Framework with Edge-Aware Preprocessing for Ground-Based Cloud Classification",
    category: "Interdisciplinary AI-Driven Systems",
    venue: "ICDMIS, Springer",
    status: "Accepted for Publication",
    year: 2025,
    authors: "Apurba Nandi, Sayantani Das, Nitu Saha, Tanisha Pan, Sukriti Sikdar, Anwesha Sinha, Tamoshree Dey",
  },
  {
    id: "r59",
    title: "A Multi-Model Approach to Mitigate Hallucinations in Large Language Models",
    category: "Interdisciplinary AI-Driven Systems",
    venue: "INDIACOM",
    status: "Accepted",
    year: 2026,
    authors: "Praneet Singh, Aditya Ghosh, Debdutta Ghosh, Satadru Pramanik, Awantika Kumari, Sayantani Das, Varsha Poddar",
  },
  {
    id: "r60",
    title: "Next-Generation Intelligent Systems: Innovations Across Emerging Technologies and Interdisciplinary Frontiers",
    category: "Interdisciplinary AI-Driven Systems",
    venue: "Bentham Science",
    status: "In Press",
    year: 2026,
    authors: "Editors: Siddhartha Roy, Sandip Mandal, Malay Gangopadhyaya, Shahab Tayeb, Aparna S. Varde",
  },
  {
    id: "r61",
    title: "Interdisciplinary Advances in AI",
    category: "Interdisciplinary AI-Driven Systems",
    venue: "Nova Science Publisher",
    status: "In Press",
    year: 2026,
    authors: "Editors: Dr. Siddhartha Roy, Dr. Malay Gangopadhyaya, Dr. Sandip Mandal",
  },
  {
    id: "r62",
    title: "Tele-Oncology in Bioinformatics",
    category: "Interdisciplinary AI-Driven Systems",
    venue: "Apple Academic Press, CRC",
    status: "Published",
    year: 2025,
    authors: "Partha Sarker, Dr. Siddhartha Roy",
  },
  {
    id: "r63",
    title: "How Intelligent Automation and Digital Technologies Reshape Industry and Society",
    category: "Interdisciplinary AI-Driven Systems",
    venue: "Scrivener Publishing",
    status: "Proposal Accepted",
    year: 2026,
    authors: "Editors: Dr. Siddhartha Roy, Dr. Sandip Mandal, Dr. Shahab Tayeb, Dr. S. Andrew Gadsden",
  },
  {
    id: "r64",
    title: "AI-Driven Photoluminescence Modeling and Experimental Study of Luminescent Silicon Quantum Dot Ink for Quantum Communication Applications",
    category: "Interdisciplinary AI-Driven Systems",
    venue: "International Conference on AI for Computing, Astronomy and Renewable Energy",
    status: "Proceedings",
    year: 2025,
    authors: "Siddhartha Roy, Susmita Biswas, Nitu Saha, Ahona Ghosh, Rangon Sarkar, Raisa Santra",
  },
  {
    id: "r65",
    title: "An Intelligent Multi-Modal AI Framework for Interview Simulation with Speech Recognition and Real-Time Feedback",
    category: "Interdisciplinary AI-Driven Systems",
    venue: "International Conference on AI for Computing, Astronomy and Renewable Energy",
    status: "Proceedings",
    year: 2025,
    authors: "Siddhartha Roy, Ahona Ghosh, Nitu Saha, Susmita Biswas, Rangon Sarkar, Tejashri Chate Srivastava",
  },
  {
    id: "r66",
    title: "Shoreline Analysis and Prediction using Canny Edge Detection",
    category: "Interdisciplinary AI-Driven Systems",
    venue: "ICISS",
    status: "Presented",
    year: 2026,
    authors: "Rohit R, Kundan Kanti Saha",
  },
  {
    id: "r67",
    title: "Fall Detection Using Vision Transformer",
    category: "Interdisciplinary AI-Driven Systems",
    venue: "CGIP, IEEE",
    status: "Presented",
    year: 2025,
    authors: "Nitu Saha, Tanmoy Kundu, Arunima Banerjee, Ahona Ghosh, Aritrik Ghosh",
  },
  {
    id: "r68",
    title: "JobLinker: Automated Recruitment through Verified Intelligence",
    category: "Interdisciplinary AI-Driven Systems",
    venue: "ICAECT",
    status: "Published",
    year: 2026,
    authors: "Uddipan Ghosh, Apalok Roy, Subhabrata Sarkar, Indrashish Bhattacharya, Soumabho Ghosh, Satakshi Shandilya",
  },
  {
    id: "r69",
    title: "Translational Roadmap of Intelligent Nanobots in Diabetes Therapy",
    category: "Interdisciplinary AI-Driven Systems",
    venue: "Scrivener",
    status: "Accepted",
    year: 2025,
    authors: "Siddhartha Roy, Susmita Biswas, Rangan Sarkar, Samrik Gosh, Arghadeep Giri, Samadrita Hazra",
  },
  {
    id: "r70",
    title: "Nanobots in Cancer Therapy and Drug Delivery",
    category: "Interdisciplinary AI-Driven Systems",
    venue: "Scrivener",
    status: "Accepted",
    year: 2025,
    authors: "Susmita Biswas, Siddhartha Roy, Rangon Sarkar, Ahona Ghosh, Samrik Gosh, Arghadeep Giri, Samadrita Hazra",
  },
  {
    id: "r71",
    title: "AgroFog+: Integrated IoT and AI System for Smart Greenhouse Management",
    category: "Interdisciplinary AI-Driven Systems",
    venue: "IEMECON",
    status: "Proceedings",
    year: 2025,
    authors: "Shibagni Bhattacharjee, Raj Krish, Debajyoti Chatterjee, Suchanda Chatterjee",
  },
  {
    id: "r72",
    title: "Machine Learning Optimized Trident Monopole Antenna for WLAN/WiMAX Applications",
    category: "Interdisciplinary AI-Driven Systems",
    venue: "IEMENTECH",
    status: "Accepted for Publication",
    year: 2026,
    authors: "Debajyoti Chatterjee, Anjan Kumar Kundu, Suchanda Chatterjee",
  },
];

const ONGOING_STATUSES = new Set<ResearchItem["status"]>([
  "Accepted",
  "Accepted for Publication",
  "In Press",
  "Proposal Accepted",
  "Accepted and Presented",
]);

export function isOngoingItem(item: ResearchItem) {
  return ONGOING_STATUSES.has(item.status);
}

export function isPublishedItem(item: ResearchItem) {
  return !isOngoingItem(item);
}
